### ISSUE TITLE
Default theme no longer working after upgrading to v2

### ISSUE THREAD

**Issue by elie222** [FormidableLabs/prism-react-renderer#212]
I fixed it with the following:

```ts
<Highlight code={code} language={codeLanguage} theme={{ plain: {}, styles: [] }}>
```

This was causing errors:

```ts
<Highlight code={code} language={codeLanguage} theme={undefined}>
```

The error was:

> Cannot destructure property 'plain' of 'theme17' as it is undefined.

**Comment by samarmeena** [comment]
```
[ERROR] Error: Cannot find module 'prism-react-renderer/themes/vsDark'
```

I am getting this.

**Comment by carloskelly13** [comment]
Please check out `2.0.5`, if you're still having issues, please open a new one. Thanks!
